#!/bin/sh
#------------------------------------------------------------------------------
# Copyright (C) 2006-2007 The ExTeX Group
#
# This library is free software; you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation; either version 2.1 of the License, or (at your option)
# any later version.
#
# This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this library; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#
#------------------------------------------------------------------------------
# THIS FILE SHOULD BE EXECUTABLE.
#------------------------------------------------------------------------------

name=$1
template=`dirname $0`/SubProject-Template.tgz

if [ "$name" = "" ] ; then
    echo "Usage:"
    echo "        $0 <projectname>"
    exit 1
fi

if [ -e $name ] ; then
    echo "$name: file exists"
    exit 1
fi

gunzip < $template | tar -xf - 
mv SubProject-Template $name
cd $name

for f in .??* * ; do
    if [ -f $f ] ; then
	/bin/mv $f xxx
	/bin/sed -e "s/xXx/$name/" xxx > $f
	/bin/rm xxx
    fi
done

#(cd ..; svn add -q $name)

mkdir target target/classes
#svn propset -q svn:ignore 'target' .

#
